/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import databaseconnect.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER
 */
public class billreservefeedback extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    /**
     * Creates new form billreservefeedback
     */
    public billreservefeedback() {
        initComponents();
        con=dbconnect.connect();
        tableload();
        
        
        datebox.setBackground(new Color(0,0,0,64));
        amountbox.setBackground(new Color(0,0,0,64));
        statusbox.setBackground(new Color(0,0,0,64));
        searchbox.setBackground(new Color(0,0,0,64));
        
         table.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
         
        table.setGridColor(Color.WHITE);
         
         table.setForeground(Color.WHITE);
         
         scroll.setBackground(new Color(0,0,0,0));
         scroll.setOpaque(false);
         table.setOpaque(false);
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setOpaque(false);
        scroll.getViewport().setOpaque(false);
    }
    public void tableload()
    {
    String sql= "select billid,billdate,totalamount,status from bill";
        try {
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
     
        
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        billbox = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        datebox = new javax.swing.JTextField();
        amountbox = new javax.swing.JTextField();
        statusbox = new javax.swing.JTextField();
        searchbox = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1104, 710));

        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Add_100px.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 150, 120, 120);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Delete_104px.png")); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(900, 340, 90, 50);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Edit_File_104px.png")); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(900, 450, 120, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Bill_35px.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 90, 35, 35);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BillDate");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 170, 100, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 250, 70, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TotalAmount");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 210, 120, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BillID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 140, 70, 20);

        billbox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        billbox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(billbox);
        billbox.setBounds(410, 140, 50, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(360, 190, 180, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(360, 240, 180, 20);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(940, 370, 0, 2);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(360, 280, 180, 30);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(320, 332, 220, 10);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Home_60px.png")); // NOI18N
        jButton5.setText("jButton5");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 30, 90, 60);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Search_35px.png")); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(540, 300, 50, 30);

        datebox.setForeground(new java.awt.Color(255, 255, 255));
        datebox.setBorder(null);
        jPanel1.add(datebox);
        datebox.setBounds(360, 162, 180, 30);

        amountbox.setForeground(new java.awt.Color(255, 255, 255));
        amountbox.setBorder(null);
        jPanel1.add(amountbox);
        amountbox.setBounds(360, 212, 180, 30);

        statusbox.setForeground(new java.awt.Color(255, 255, 255));
        statusbox.setBorder(null);
        jPanel1.add(statusbox);
        statusbox.setBounds(360, 252, 180, 30);

        searchbox.setForeground(new java.awt.Color(255, 255, 255));
        searchbox.setBorder(null);
        jPanel1.add(searchbox);
        searchbox.setBounds(320, 302, 220, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scroll.setViewportView(table);

        jPanel1.add(scroll);
        scroll.setBounds(182, 360, 670, 350);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\gui\\bmw2.jpg")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1104, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1104, 720));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String date= datebox.getText();
        String amount= amountbox.getText();
        String status= statusbox.getText();
       
        try {
            
        String q= "insert into bill (billdate,totalamount,status) values('"+date+"','"+amount+"','"+status+"')";
        pst=con.prepareStatement(q);
        pst.execute();
         tableload();
        
        } catch (Exception e) {
        }        

    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      int x=JOptionPane.showConfirmDialog(null,"Do you want to delete?");
       
       
       if(x==0)
       {
       
       String id=billbox.getText();
       String sql="delete from bill where billid='"+id+"'";
           try {
               pst=con.prepareStatement(sql);
               pst.execute();
               tableload();
               
           } catch (Exception e) {
           }
       
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       maininterface main=new maininterface();
       main.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int a=JOptionPane.showConfirmDialog(null, "Do you want to update?");
       
       if(a==0)
       {
       String id=billbox.getText();
       String date=datebox.getText();
       String amount=amountbox.getText();
       String status=statusbox.getText();
       
       String sql="UPDATE bill set billid='"+id+"', billdate='"+date+"', totalamount='"+amount+"', status='"+status+"'";
       
           try {
          pst=con.prepareStatement(sql);
          pst.executeUpdate();
          tableload();
           } catch (Exception e) {
           }
       
       
       
       
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
         int r=table.getSelectedRow();
        String id= table.getValueAt(r, 0).toString();
        String date= table.getValueAt(r, 1).toString();
        String totalamount= table.getValueAt(r, 2).toString();
        String status=table.getValueAt(r,3).toString();
        
        
        
        
         billbox.setText(id);
         datebox.setText(date);
         amountbox.setText(totalamount);
         statusbox.setText(status);
         
              
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billreservefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billreservefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billreservefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billreservefeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billreservefeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountbox;
    private javax.swing.JLabel billbox;
    private javax.swing.JTextField datebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField statusbox;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
