/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import databaseconnect.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER
 */
public class car extends javax.swing.JFrame {

    /**
     * Creates new form car
     */
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    public car() {
        initComponents();
         con=dbconnect.connect();
         tableload();
        
        
             regbox.setBackground(new Color(0,0,0,64));
         typebox.setBackground(new Color(0,0,0,64)); 
         modelbox.setBackground(new Color(0,0,0,64));
         transmissionbox.setBackground(new Color(0,0,0,64));
         insurancebox.setBackground(new Color(0,0,0,64));
         fuelbox.setBackground(new Color(0,0,0,64));   
         searchbox.setBackground(new Color(0,0,0,64));
         
          table.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
         
        table.setGridColor(Color.WHITE);
         
         table.setForeground(Color.WHITE);
         
         scroll.setBackground(new Color(0,0,0,0));
         scroll.setOpaque(false);
         table.setOpaque(false);
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setOpaque(false);
        scroll.getViewport().setOpaque(false);
                
                 
         
    }
     public void tableload()
    {
        try {
            String sql= "select carid,regnumber,type,model,transmission,insurance,fuel from car";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();  //assign rs variable
            
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
    
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        search = new javax.swing.JButton();
        caridbox = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        typebox = new javax.swing.JTextField();
        modelbox = new javax.swing.JTextField();
        transmissionbox = new javax.swing.JTextField();
        regbox = new javax.swing.JTextField();
        insurancebox = new javax.swing.JTextField();
        fuelbox = new javax.swing.JTextField();
        searchbox = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FuelConsumption");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(180, 380, 148, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Insurance");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(180, 340, 82, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transmission");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(180, 300, 110, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Model");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(180, 260, 53, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 220, 40, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RegistrationNum");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 180, 142, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CarID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 140, 90, 25);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Home_60px.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 20, 90, 70);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(370, 200, 270, 10);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(370, 240, 270, 10);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(370, 280, 270, 0);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(370, 320, 270, 10);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(370, 360, 270, 10);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(370, 400, 270, 30);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(370, 460, 240, 10);

        search.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Search_35px.png")); // NOI18N
        search.setText("jButton2");
        search.setBorder(null);
        search.setContentAreaFilled(false);
        jPanel1.add(search);
        search.setBounds(610, 430, 50, 30);

        caridbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        caridbox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(caridbox);
        caridbox.setBounds(440, 120, 50, 40);

        edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Car_Service_60px.png")); // NOI18N
        edit.setText("jButton5");
        edit.setBorder(null);
        edit.setContentAreaFilled(false);
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(940, 400, 70, 60);

        add.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Car_60px.png")); // NOI18N
        add.setText("jButton3");
        add.setContentAreaFilled(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(940, 170, 80, 60);

        delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Trash_64px.png")); // NOI18N
        delete.setText("jButton4");
        delete.setBorder(null);
        delete.setContentAreaFilled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(940, 270, 100, 90);

        typebox.setBackground(new java.awt.Color(0, 0, 0));
        typebox.setForeground(new java.awt.Color(255, 255, 255));
        typebox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typebox.setBorder(null);
        jPanel1.add(typebox);
        typebox.setBounds(370, 210, 270, 30);

        modelbox.setBackground(new java.awt.Color(0, 0, 0));
        modelbox.setForeground(new java.awt.Color(255, 255, 255));
        modelbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modelbox.setBorder(null);
        jPanel1.add(modelbox);
        modelbox.setBounds(370, 246, 270, 30);

        transmissionbox.setBackground(new java.awt.Color(0, 0, 0));
        transmissionbox.setForeground(new java.awt.Color(255, 255, 255));
        transmissionbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transmissionbox.setBorder(null);
        jPanel1.add(transmissionbox);
        transmissionbox.setBounds(370, 290, 270, 30);

        regbox.setBackground(new java.awt.Color(0, 0, 0));
        regbox.setForeground(new java.awt.Color(255, 255, 255));
        regbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        regbox.setBorder(null);
        regbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regboxActionPerformed(evt);
            }
        });
        jPanel1.add(regbox);
        regbox.setBounds(370, 172, 270, 30);

        insurancebox.setBackground(new java.awt.Color(0, 0, 0));
        insurancebox.setForeground(new java.awt.Color(255, 255, 255));
        insurancebox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        insurancebox.setBorder(null);
        jPanel1.add(insurancebox);
        insurancebox.setBounds(370, 330, 270, 30);

        fuelbox.setBackground(new java.awt.Color(0, 0, 0));
        fuelbox.setForeground(new java.awt.Color(255, 255, 255));
        fuelbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fuelbox.setBorder(null);
        jPanel1.add(fuelbox);
        fuelbox.setBounds(370, 370, 270, 30);

        searchbox.setBackground(new java.awt.Color(0, 0, 0));
        searchbox.setForeground(new java.awt.Color(255, 255, 255));
        searchbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchbox.setBorder(null);
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        jPanel1.add(searchbox);
        searchbox.setBounds(370, 430, 240, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        scroll.setViewportView(table);

        jPanel1.add(scroll);
        scroll.setBounds(120, 470, 710, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\gui\\mustang2.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        maininterface main=new maininterface();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
          String regnumber= regbox.getText();
        String type= typebox.getText();
        String model= modelbox.getText();
        String transmission= transmissionbox.getText();
          String insurance= insurancebox.getText();
            String fuel= fuelbox.getText();
        
       
            
        String q= "insert into car (regnumber,type,model,transmission,insurance,fuel) values('"+regnumber+"','"+type+"','"+model+"','"+transmission+"','"+insurance+"','"+fuel+"')";
        try {
               pst=con.prepareStatement(q);
               pst.execute();
               tableload();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addActionPerformed

    private void regboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regboxActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
         String name=searchbox.getText();
         String sql="select carid,regnumber,type,model,transmission,insurance,fuelconsumption from car where model LIKE '%"+name+"%'";
       
             try {
             pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         
         table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_searchboxActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
         int a =JOptionPane.showConfirmDialog(null,"Do you want to update!");
        
       if(a==0)
       {
        String id=regbox.getText();
        String type= typebox.getText();
        String model= modelbox.getText();
        String transmission= transmissionbox.getText();
        String insurance= insurancebox.getText();
        String fuel= fuelbox.getText();
        
        String sql= "UPDATE car SET regnumber='"+id+"', type= '"+type+"', model= '"+model+"', transmission= '"+transmission+"', insurance= '"+insurance+"', fuel='"+fuel+"' where carid= '"+id+"'";
          
              try {
                 pst=con.prepareStatement(sql);
                pst.executeUpdate(sql);
                tableload();
           } catch (Exception e) {
           }
    }//GEN-LAST:event_editActionPerformed
    }
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int x=JOptionPane.showConfirmDialog(null,"Do you want to delete?");
       
       
       if(x==0)
       {
       
       String id=caridbox.getText();
       String abc="delete from car where carid='"+id+"'";
       
           try {
               pst=con.prepareStatement(abc);
               pst.execute();a
               tableload();
           } catch (Exception e) {
           }
    }//GEN-LAST:event_deleteActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel caridbox;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField fuelbox;
    private javax.swing.JTextField insurancebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField modelbox;
    private javax.swing.JTextField regbox;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTable table;
    private javax.swing.JTextField transmissionbox;
    private javax.swing.JTextField typebox;
    // End of variables declaration//GEN-END:variables
}
