/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import databaseconnect.dbconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER
 */
public class emp extends javax.swing.JFrame {

      Connection con=null;
      PreparedStatement pst=null;
      ResultSet rs =null;
    
    public emp() {
        initComponents();
         con=dbconnect.connect();
         tableload();//load the table
         
         
        fnamebox.setBackground(new Color(0,0,0,64));
        lnamebox.setBackground(new Color(0,0,0,64));
        positionbox.setBackground(new Color(0,0,0,64));
        searchbox.setBackground(new Color(0,0,0,64));
          table.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
         
        table.setGridColor(Color.WHITE);
         
         table.setForeground(Color.WHITE);
         
         scroll.setBackground(new Color(0,0,0,0));
         scroll.setOpaque(false);
         table.setOpaque(false);
        ((DefaultTableCellRenderer)table.getDefaultRenderer(Object.class)).setOpaque(false);
        scroll.getViewport().setOpaque(false);
        
        
    }
    public void tableload()
    {
        try {
             String sql="select employeeid,firstname,lastname,position from employee";
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
    
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        fnamebox = new javax.swing.JTextField();
        lnamebox = new javax.swing.JTextField();
        positionbox = new javax.swing.JTextField();
        searchbox = new javax.swing.JTextField();
        employeeidbox = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1104, 710));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EmployeeID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 140, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FirstName");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 200, 85, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LastName");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 250, 83, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 300, 68, 25);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Delete_35px.png")); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(810, 270, 119, 43);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Edit_File_64px.png")); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(830, 350, 97, 73);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Search_35px.png")); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(560, 380, 50, 30);

        fnamebox.setBackground(new java.awt.Color(0, 0, 0));
        fnamebox.setForeground(new java.awt.Color(255, 255, 255));
        fnamebox.setBorder(null);
        fnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameboxActionPerformed(evt);
            }
        });
        jPanel1.add(fnamebox);
        fnamebox.setBounds(360, 190, 200, 30);

        lnamebox.setBackground(new java.awt.Color(0, 0, 0));
        lnamebox.setForeground(new java.awt.Color(255, 255, 255));
        lnamebox.setBorder(null);
        lnamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameboxActionPerformed(evt);
            }
        });
        jPanel1.add(lnamebox);
        lnamebox.setBounds(360, 250, 200, 30);

        positionbox.setBackground(new java.awt.Color(0, 0, 0));
        positionbox.setForeground(new java.awt.Color(255, 255, 255));
        positionbox.setBorder(null);
        positionbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionboxActionPerformed(evt);
            }
        });
        jPanel1.add(positionbox);
        positionbox.setBounds(360, 310, 200, 30);

        searchbox.setBackground(new java.awt.Color(0, 0, 0));
        searchbox.setForeground(new java.awt.Color(255, 255, 255));
        searchbox.setBorder(null);
        jPanel1.add(searchbox);
        searchbox.setBounds(360, 380, 200, 30);

        employeeidbox.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        employeeidbox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(employeeidbox);
        employeeidbox.setBounds(370, 140, 80, 20);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Add_User_Male_48px.png")); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(830, 160, 100, 80);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scroll.setViewportView(table);

        jPanel1.add(scroll);
        scroll.setBounds(250, 420, 550, 250);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\icons8_Home_60px.png")); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 30, 80, 90);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\gui\\benz112.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         String name=searchbox.getText();
         String sql="select employeeid,firstname,lastname,position from employee where firstname LIKE '%"+name+"%'";
        try {
              pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
          table.setModel(DbUtils.resultSetToTableModel(rs));
         
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameboxActionPerformed

    private void positionboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
         int a =JOptionPane.showConfirmDialog(null,"Do you want to update!");
         
          if(a==0)
       {
        String id=employeeidbox.getText();
        String fname= fnamebox.getText();
        String lname= lnamebox.getText();
        String position = positionbox.getText();

        
        String sql= "UPDATE employee SET firstname= '"+fname+"', lastname= '"+lname+"', position = '"+position+"' where employeeid= '"+id+"'";
        
           try {
                pst=con.prepareStatement(sql);
                pst.executeUpdate(sql);
                tableload();
          
           } catch (Exception e) {
           }
    }//GEN-LAST:event_jButton3ActionPerformed
   }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        int x=JOptionPane.showConfirmDialog(null,"Do you want to delete?");
       
       
       if(x==0)
       {
       
       String id=employeeidbox.getText();
       String sql="delete from employee where employeeid='"+id+"'";
           try {
               pst=con.prepareStatement(sql);
               pst.execute();
               tableload();
            
               }
           catch (Exception e) {
           }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           String fname= fnamebox.getText();
        String lname= lnamebox.getText();
        String position= positionbox.getText();
        
        
      
        String q= "insert into employee (firstname,lastname,position) value('"+fname+"','"+lname+"','"+position+"')";
       
        try {
               pst=con.prepareStatement(q);
               pst.execute();
               tableload();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       int r=table.getSelectedRow();
        String id= table.getValueAt(r, 0).toString();
        String fname= table.getValueAt(r, 1).toString();
        String lname= table.getValueAt(r, 2).toString();
        String position= table.getValueAt(r, 3).toString();
         
         
         employeeidbox.setText(id);
         fnamebox.setText(fname);
         lnamebox.setText(lname);
         positionbox.setText(position);
     
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        maininterface main=new maininterface();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employeeidbox;
    private javax.swing.JTextField fnamebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JTextField positionbox;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
